FROM eclipse-mosquitto:latest

ARG WORKDIR=/home/mosquitto

WORKDIR $WORKDIR

COPY entrypoint.sh ${WORKDIR}/entrypoint.sh

RUN chmod +x ${WORKDIR}/entrypoint.sh &&\ 
    mkdir ${WORKDIR}/config ${WORKDIR}/acl ${WORKDIR}/passwords

RUN chown -R mosquitto:mosquitto ${WORKDIR}

USER mosquitto

EXPOSE 1883
EXPOSE 9001

CMD ["/usr/sbin/mosquitto", "-c", "/home/mosquitto/config/mosquitto.conf"]
