FROM eclipse-mosquitto:latest

ARG WORKDIR=/home/mosquitto

WORKDIR $WORKDIR

RUN mkdir ${WORKDIR}/config ${WORKDIR}/acl ${WORKDIR}/passwords

RUN chown -R mosquitto:mosquitto ${WORKDIR}

USER mosquitto

EXPOSE 1883
EXPOSE 8083

CMD ["/usr/sbin/mosquitto", "-c", "/home/mosquitto/config/mosquitto.conf"]
