plaintext
@startuml
skinparam backgroundColor transparent
actor Publisher
participant "Mosquitto Broker" as Broker
actor Subscriber
database "IBM Cloudant DB" as Cloudant

Publisher -> Broker: Publish msg (MQTT/1883 and websockets/8083)
Broker -> Subscriber: Push msg(Subscribed to Topic)
Subscriber -> Subscriber: Process and handle msg
Subscriber -> Cloudant: Store msg in DB
Cloudant -> Subscriber: Acknowledge storage
@enduml